name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - 'v*' # version-tagged commits are releases which have their own workflow
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install && pnpm run ci
